  -- Drop tables before creating them.
DROP TABLE IF EXISTS MATCH;
DROP TABLE IF EXISTS TOURNAMENT;
DROP TABLE IF EXISTS PLAYER;
DROP TABLE IF EXISTS IN_PLAY_DATA;

-- Contains player info
CREATE TABLE PLAYER(
    [PLAYER_ID] [INT] IDENTITY(1,1) NOT NULL PRIMARY KEY,
    [PLAYER_NAME] [VARCHAR](50) NOT NULL,
    [PLAYER_ELO] INT,
    [PLAYER_PRIMARY_HAND] [VARCHAR](5)
);

-- Holds name of tournament
CREATE TABLE TOURNAMENT(
    TOURNAMENT_ID INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
    TOURNAMENT_NAME [VARCHAR](50) NOT NULL
);

-- Holds the players in the match as well as tournament the match was a part of
CREATE TABLE MATCH(
    MATCH_ID INT IDENTITY(1,1) PRIMARY KEY,
    TOURNAMENT_ID INT,
    PLAYER_ONE_ID INT,
    PLAYER_TWO_ID INT,
    FOREIGN KEY (TOURNAMENT_ID) REFERENCES TOURNAMENT(TOURNAMENT_ID),
    FOREIGN KEY (PLAYER_ONE_ID) REFERENCES PLAYER(PLAYER_ID),
    FOREIGN KEY (PLAYER_TWO_ID) REFERENCES PLAYER(PLAYER_ID)
);

-- Contains data about the match
CREATE TABLE IN_PLAY_DATA(
    IN_PLAY_DATA_ID INT IDENTITY(1,1) PRIMARY KEY,
    MATCH_ID INT,
    SET_NUMBER INT,
    PLAYER_ONE_GAMES_WON INT,
    PLAYER_TWO_GAMES_WON INT,
    SET_WINNER INT,
    GAME_NUMBER INT,
    GAME_WINNER INT,
    POINT_NUMBER INT,
    POINT_WINNER INT,
    POINT_SERVER INT,
    PLAYER_ONE_SCORE VARCHAR(10),
    PLAYER_TWO_SCORE VARCHAR(10),
    GAME_STATUS VARCHAR(20),
    FOREIGN KEY (MATCH_ID) REFERENCES MATCH(MATCH_ID)
);

