DROP TABLE dbo.IN_PLAY_DATA;

CREATE TABLE dbo.IN_PLAY_DATA(
    IN_PLAY_DATA_ID INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
    IN_PLAY_DATA_KEY VARCHAR(100),
    SET_NUMBER INT,
    PLAYER_ONE_GAMES_WON INT,
    PLAYER_TWO_GAMES_WON INT,
    SET_WINNER INT,
    GAME_NUMBER INT,
    GAME_WINNER INT,
    POINT_NUMBER INT,
    POINT_WINNER INT,
    POINT_SERVER INT,
    PLAYER_ONE_SCORE VARCHAR(10),
    PLAYER_TWO_SCORE VARCHAR(10),
    GAME_STATUS VARCHAR(20),
);
